/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as StaffRouteRouteImport } from './routes/staff/route'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as StudentVisaRouteImport } from './routes/student-visa'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as UniversitiesRouteImport } from './routes/universities'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminConsultantsRouteImport } from './routes/admin/consultants'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminImportExportRouteImport } from './routes/admin/import-export'
import { Route as AdminLeaderboardRouteImport } from './routes/admin/leaderboard'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminProgramsRouteImport } from './routes/admin/programs'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminScholarshipsRouteImport } from './routes/admin/scholarships'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminUniversitiesRouteImport } from './routes/admin/universities'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffActivityRouteImport } from './routes/staff/activity'
import { Route as StaffApplicationsRouteImport } from './routes/staff/applications'
import { Route as StaffAppointmentsRouteImport } from './routes/staff/appointments'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as StaffDocumentsRouteImport } from './routes/staff/documents'
import { Route as StaffLeadsRouteImport } from './routes/staff/leads'
import { Route as StaffStudentsRouteImport } from './routes/staff/students'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentApplicationsRouteImport } from './routes/student/applications'
import { Route as StudentAppointmentsRouteImport } from './routes/student/appointments'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as StudentDocumentsRouteImport } from './routes/student/documents'
import { Route as StudentNotificationsRouteImport } from './routes/student/notifications'
import { Route as StudentProfileRouteImport } from './routes/student/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentVisaRoute = StudentVisaRouteImport.update({
  id: '/student-visa',
  path: '/student-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesRoute = UniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConsultantsRoute = AdminConsultantsRouteImport.update({
  id: '/consultants',
  path: '/consultants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportExportRoute = AdminImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeaderboardRoute = AdminLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProgramsRoute = AdminProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminScholarshipsRoute = AdminScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUniversitiesRoute = AdminUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffActivityRoute = StaffActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffApplicationsRoute = StaffApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffAppointmentsRoute = StaffAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffDocumentsRoute = StaffDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffLeadsRoute = StaffLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffStudentsRoute = StaffStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentApplicationsRoute = StudentApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAppointmentsRoute = StudentAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentDocumentsRoute = StudentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentNotificationsRoute = StudentNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/student-visa': typeof StudentVisaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/import-export': typeof AdminImportExportRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/applications': typeof StaffApplicationsRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/documents': typeof StaffDocumentsRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/students': typeof StaffStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/appointments': typeof StudentAppointmentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/student-visa': typeof StudentVisaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/import-export': typeof AdminImportExportRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/applications': typeof StaffApplicationsRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/documents': typeof StaffDocumentsRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/students': typeof StaffStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/appointments': typeof StudentAppointmentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin': typeof AdminIndexRoute
  '/staff': typeof StaffIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/staff': typeof StaffRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/programs': typeof ProgramsRoute
  '/resources': typeof ResourcesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/services': typeof ServicesRoute
  '/student-visa': typeof StudentVisaRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/universities': typeof UniversitiesRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/import-export': typeof AdminImportExportRoute
  '/admin/leaderboard': typeof AdminLeaderboardRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/programs': typeof AdminProgramsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/scholarships': typeof AdminScholarshipsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/staff/activity': typeof StaffActivityRoute
  '/staff/applications': typeof StaffApplicationsRoute
  '/staff/appointments': typeof StaffAppointmentsRoute
  '/staff/dashboard': typeof StaffDashboardRoute
  '/staff/documents': typeof StaffDocumentsRoute
  '/staff/leads': typeof StaffLeadsRoute
  '/staff/students': typeof StaffStudentsRoute
  '/student/applications': typeof StudentApplicationsRoute
  '/student/appointments': typeof StudentAppointmentsRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/notifications': typeof StudentNotificationsRoute
  '/student/profile': typeof StudentProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/staff'
    | '/student'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/programs'
    | '/resources'
    | '/scholarships'
    | '/services'
    | '/student-visa'
    | '/success-stories'
    | '/universities'
    | '/admin/applications'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/consultants'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/import-export'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/scholarships'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/universities'
    | '/staff/activity'
    | '/staff/applications'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/documents'
    | '/staff/leads'
    | '/staff/students'
    | '/student/applications'
    | '/student/appointments'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/notifications'
    | '/student/profile'
    | '/admin/'
    | '/staff/'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/programs'
    | '/resources'
    | '/scholarships'
    | '/services'
    | '/student-visa'
    | '/success-stories'
    | '/universities'
    | '/admin/applications'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/consultants'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/import-export'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/scholarships'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/universities'
    | '/staff/activity'
    | '/staff/applications'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/documents'
    | '/staff/leads'
    | '/staff/students'
    | '/student/applications'
    | '/student/appointments'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/notifications'
    | '/student/profile'
    | '/admin'
    | '/staff'
    | '/student'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/staff'
    | '/student'
    | '/about'
    | '/contact'
    | '/destinations'
    | '/programs'
    | '/resources'
    | '/scholarships'
    | '/services'
    | '/student-visa'
    | '/success-stories'
    | '/universities'
    | '/admin/applications'
    | '/admin/appointments'
    | '/admin/audit-logs'
    | '/admin/consultants'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/import-export'
    | '/admin/leaderboard'
    | '/admin/leads'
    | '/admin/notifications'
    | '/admin/programs'
    | '/admin/reports'
    | '/admin/scholarships'
    | '/admin/settings'
    | '/admin/students'
    | '/admin/universities'
    | '/staff/activity'
    | '/staff/applications'
    | '/staff/appointments'
    | '/staff/dashboard'
    | '/staff/documents'
    | '/staff/leads'
    | '/staff/students'
    | '/student/applications'
    | '/student/appointments'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/notifications'
    | '/student/profile'
    | '/admin/'
    | '/staff/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  ProgramsRoute: typeof ProgramsRoute
  ResourcesRoute: typeof ResourcesRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  ServicesRoute: typeof ServicesRoute
  StudentVisaRoute: typeof StudentVisaRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  UniversitiesRoute: typeof UniversitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-visa': {
      id: '/student-visa'
      path: '/student-visa'
      fullPath: '/student-visa'
      preLoaderRoute: typeof StudentVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities': {
      id: '/universities'
      path: '/universities'
      fullPath: '/universities'
      preLoaderRoute: typeof UniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/consultants': {
      id: '/admin/consultants'
      path: '/consultants'
      fullPath: '/admin/consultants'
      preLoaderRoute: typeof AdminConsultantsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/import-export': {
      id: '/admin/import-export'
      path: '/import-export'
      fullPath: '/admin/import-export'
      preLoaderRoute: typeof AdminImportExportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leaderboard': {
      id: '/admin/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLeaderboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/programs': {
      id: '/admin/programs'
      path: '/programs'
      fullPath: '/admin/programs'
      preLoaderRoute: typeof AdminProgramsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/scholarships': {
      id: '/admin/scholarships'
      path: '/scholarships'
      fullPath: '/admin/scholarships'
      preLoaderRoute: typeof AdminScholarshipsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/universities': {
      id: '/admin/universities'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AdminUniversitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/activity': {
      id: '/staff/activity'
      path: '/activity'
      fullPath: '/staff/activity'
      preLoaderRoute: typeof StaffActivityRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/applications': {
      id: '/staff/applications'
      path: '/applications'
      fullPath: '/staff/applications'
      preLoaderRoute: typeof StaffApplicationsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/appointments': {
      id: '/staff/appointments'
      path: '/appointments'
      fullPath: '/staff/appointments'
      preLoaderRoute: typeof StaffAppointmentsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/documents': {
      id: '/staff/documents'
      path: '/documents'
      fullPath: '/staff/documents'
      preLoaderRoute: typeof StaffDocumentsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/leads': {
      id: '/staff/leads'
      path: '/leads'
      fullPath: '/staff/leads'
      preLoaderRoute: typeof StaffLeadsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/staff/students': {
      id: '/staff/students'
      path: '/students'
      fullPath: '/staff/students'
      preLoaderRoute: typeof StaffStudentsRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/applications': {
      id: '/student/applications'
      path: '/applications'
      fullPath: '/student/applications'
      preLoaderRoute: typeof StudentApplicationsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/appointments': {
      id: '/student/appointments'
      path: '/appointments'
      fullPath: '/student/appointments'
      preLoaderRoute: typeof StudentAppointmentsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/documents': {
      id: '/student/documents'
      path: '/documents'
      fullPath: '/student/documents'
      preLoaderRoute: typeof StudentDocumentsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/notifications': {
      id: '/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentNotificationsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminConsultantsRoute: typeof AdminConsultantsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminImportExportRoute: typeof AdminImportExportRoute
  AdminLeaderboardRoute: typeof AdminLeaderboardRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProgramsRoute: typeof AdminProgramsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScholarshipsRoute: typeof AdminScholarshipsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminUniversitiesRoute: typeof AdminUniversitiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminConsultantsRoute: AdminConsultantsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminImportExportRoute: AdminImportExportRoute,
  AdminLeaderboardRoute: AdminLeaderboardRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProgramsRoute: AdminProgramsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScholarshipsRoute: AdminScholarshipsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminUniversitiesRoute: AdminUniversitiesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffActivityRoute: typeof StaffActivityRoute
  StaffApplicationsRoute: typeof StaffApplicationsRoute
  StaffAppointmentsRoute: typeof StaffAppointmentsRoute
  StaffDashboardRoute: typeof StaffDashboardRoute
  StaffDocumentsRoute: typeof StaffDocumentsRoute
  StaffLeadsRoute: typeof StaffLeadsRoute
  StaffStudentsRoute: typeof StaffStudentsRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffActivityRoute: StaffActivityRoute,
  StaffApplicationsRoute: StaffApplicationsRoute,
  StaffAppointmentsRoute: StaffAppointmentsRoute,
  StaffDashboardRoute: StaffDashboardRoute,
  StaffDocumentsRoute: StaffDocumentsRoute,
  StaffLeadsRoute: StaffLeadsRoute,
  StaffStudentsRoute: StaffStudentsRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface StudentRouteRouteChildren {
  StudentApplicationsRoute: typeof StudentApplicationsRoute
  StudentAppointmentsRoute: typeof StudentAppointmentsRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentDocumentsRoute: typeof StudentDocumentsRoute
  StudentNotificationsRoute: typeof StudentNotificationsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentApplicationsRoute: StudentApplicationsRoute,
  StudentAppointmentsRoute: StudentAppointmentsRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentDocumentsRoute: StudentDocumentsRoute,
  StudentNotificationsRoute: StudentNotificationsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  ProgramsRoute: ProgramsRoute,
  ResourcesRoute: ResourcesRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  ServicesRoute: ServicesRoute,
  StudentVisaRoute: StudentVisaRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  UniversitiesRoute: UniversitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
